export { default as Header } from './Header/Header'
export { default as Footer } from './Footer/Footer'
export { default as MainButton } from './Buttons/Buttons'
export { SubButton as SubButton } from './Buttons/Buttons'
export { DownloadButton as DownloadButton } from './Buttons/Buttons'