export { default as AboutMe } from '../Sections/AboutMe/AboutMe'
export { default as Hero } from '../Sections/Hero/Hero'
export { default as Skills } from '../Sections/Skills/Skills'
export { default as Portfolio } from '../Sections/Portfolio/Portfolio'
export { default as EducationAndTrining } from '../Sections/EducationAndTrining/EducationAndTrining'
export { default as GetInTouch } from '../Sections/GetInTouch/GetInTouch'
export { default as Services } from '../Sections/Services/Services'